name: 'Azure VM deployment'
description: 'Deploy a VM to Azure'
inputs:
    azure-resource-group:
        description: 'Azure resource group'
        required: true
        default: 'GithubActionsRG'
    azure-vm-name:
        description: 'Azure VM name'
        required: true
        default: 'GithubActionsVM'
    azure-vm-size:
        description: 'Azure VM size'
        required: true
        default: 'Standard_DS2_v2'
outputs:
    stdout:
        description: 'Stdout'
    stderr:
        description: 'Stderr'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.azure-resource-group }}
        - ${{ inputs.azure-vm-name }}
        - ${{ inputs.azure-vm-size }}