name: 'Azure VM deployment'
description: 'Deploy a VM to Azure'
inputs:
    azure-resource-group:
        description: 'Azure resource group'
        required: true
        default: 'GithubActionsRG'
    azure-vm-name:
        description: 'Azure VM name'
        required: true
        default: 'GithubActionsVM'
    azure-vm-size:
        description: 'Azure VM size'
        required: true
        default: 'Standard_DS2_v2'
outputs:
    stdout:
        description: 'Stdout'
    stderr:
        description: 'Stderr'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        # - -v /home/runner/.azure:/root/.azure
        - ${{ inputs.azure-resource-group }}
        - ${{ inputs.azure-vm-name }}
        - ${{ inputs.azure-vm-size }}

# default mounts
# -v "/var/run/docker.sock":"/var/run/docker.sock"
# -v "/home/runner/work/_temp/_github_home":"/github/home"
# -v "/home/runner/work/_temp/_github_workflow":"/github/workflow"
# -v "/home/runner/work/devito/devito":"/github/workspace"